//список всех полученных ингредиентов
export const ALL_GET_INGREDIENTS_REQUEST: 'ALL_GET_INGREDIENTS_REQUEST' = 'ALL_GET_INGREDIENTS_REQUEST';
export const ALL_GET_INGREDIENTS_SUCCESS: 'ALL_GET_INGREDIENTS_SUCCESS' = 'ALL_GET_INGREDIENTS_SUCCESS';
export const ALL_GET_INGREDIENTS_FAILURE: 'ALL_GET_INGREDIENTS_FAILURE' = 'ALL_GET_INGREDIENTS_FAILURE';
//список всех ингредиентов в текущем конструкторе бургера
export const IN_CONSTRUCTOR_BUNS: 'IN_CONSTRUCTOR_BUNS' = 'IN_CONSTRUCTOR_BUNS';
export const IN_CONSTRUCTOR_MAIN: 'IN_CONSTRUCTOR_MAIN' = 'IN_CONSTRUCTOR_MAIN';
export const IN_CONSTRUCTOR_DELETE_INGREDIENT: 'IN_CONSTRUCTOR_DELETE_INGREDIENT' = 'IN_CONSTRUCTOR_DELETE_INGREDIENT';
export const IN_CONSTRUCTOR_MOVE_INGREDIENT: 'IN_CONSTRUCTOR_MOVE_INGREDIENT' = 'IN_CONSTRUCTOR_MOVE_INGREDIENT';
export const IN_CONSTRUCTOR_CLEAN: 'IN_CONSTRUCTOR_CLEAN' = 'IN_CONSTRUCTOR_CLEAN';
//для модальных окон
export const IN_MODAL_OPEN_INGREDIENT_CARD: 'IN_MODAL_OPEN_INGREDIENT_CARD' = 'IN_MODAL_OPEN_INGREDIENT_CARD';
export const IN_MODAL_OPEN_ORDER_CARD: 'IN_MODAL_OPEN_ORDER_CARD' = 'IN_MODAL_OPEN_ORDER_CARD';
export const IN_MODAL_CLOSE_CARD: 'IN_MODAL_CLOSE_CARD' = 'IN_MODAL_CLOSE_CARD';
export const IN_MODAL_ACTIVE: 'IN_MODAL_ACTIVE' = 'IN_MODAL_ACTIVE';
export const IN_MODAL_OPEN_HISTORY_ORDER_CARD: 'IN_MODAL_OPEN_HISTORY_ORDER_CARD' = 'IN_MODAL_OPEN_HISTORY_ORDER_CARD';
//номер заказа
export const ORDER_GET_ORDER_NUMBER_REQUEST: 'ORDER_GET_ORDER_NUMBER_REQUEST' = 'ORDER_GET_ORDER_NUMBER_REQUEST';
export const ORDER_GET_ORDER_NUMBER_SUCCESS: 'ORDER_GET_ORDER_NUMBER_SUCCESS'  = 'ORDER_GET_ORDER_NUMBER_SUCCESS';
export const ORDER_GET_ORDER_NUMBER_FAILURE: 'ORDER_GET_ORDER_NUMBER_FAILURE'  = 'ORDER_GET_ORDER_NUMBER_FAILURE';
export const TOTAL_PRICE_ORDER: 'TOTAL_PRICE_ORDER' = 'TOTAL_PRICE_ORDER';
export const GET_ORDER_INFO_SUCCESS: 'GET_ORDER_INFO_SUCCESS' = 'GET_ORDER_INFO_SUCCESS';
export const GET_ORDER_INFO_FAILURE: 'GET_ORDER_INFO_FAILURE' = 'GET_ORDER_INFO_FAILURE';
//drop
export const DROP_CARD: 'DROP_CARD' = 'DROP_CARD';
export const DROP_INGREDIENT: 'DROP_INGREDIENT' = 'DROP_INGREDIENT';
//выбранный ингредиент
export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
//выбранный заказ из списка
export const SET_CURRENT_HISTORY_ORDER: 'SET_CURRENT_HISTORY_ORDER' = 'SET_CURRENT_HISTORY_ORDER';
//инпуты
export const INPUT_USER_NAME: 'INPUT_USER_NAME' = 'INPUT_USER_NAME';
export const INPUT_USER_PASSWORD: 'INPUT_USER_PASSWORD' = 'INPUT_USER_PASSWORD';
export const INPUT_USER_EMAIL: 'INPUT_USER_EMAIL' = 'INPUT_USER_EMAIL';
export const INPUT_VERIFICATION_CODE: 'INPUT_VERIFICATION_CODE' = 'INPUT_VERIFICATION_CODE';
export const INPUT_CLEAN_DATA: 'INPUT_CLEAN_DATA' = 'INPUT_CLEAN_DATA';
//юзер регистрация
export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE: 'REGISTER_FAILURE' = 'REGISTER_FAILURE';
//забыл пароль
export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE' = "FORGOT_PASSWORD_FAILURE";
//сброс пароля
export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE' = "RESET_PASSWORD_FAILURE";
// юзер логин/логаут
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE: 'LOGIN_FAILURE' = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE: 'LOGOUT_FAILURE' = 'LOGOUT_FAILURE';
//получить данные пользователя
export const GET_USERDATA_REQUEST: 'GET_USERDATA_REQUEST' = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS: 'GET_USERDATA_SUCCESS' = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILURE: 'GET_USERDATA_FAILURE' = 'GET_USERDATA_FAILURE';
//изменить данные пользователя
export const CHANGE_USERDATA_REQUEST: 'CHANGE_USERDATA_REQUEST' = 'CHANGE_USERDATA_REQUEST';
export const CHANGE_USERDATA_SUCCESS: 'CHANGE_USERDATA_SUCCESS' = 'CHANGE_USERDATA_SUCCESS';
export const CHANGE_USERDATA_FAILURE: 'CHANGE_USERDATA_FAILURE' = 'CHANGE_USERDATA_FAILURE';
//для рефреш токена
export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE' = 'REFRESH_TOKEN_FAILURE';
//вебсокет
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE' = 'WS_CONNECTION_CLOSE';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_GET_USER_ORDERS: 'WS_GET_USER_ORDERS' = 'WS_GET_USER_ORDERS';
export const WS_SEND_MESSAGE: 'WS_SEND_MESSAGE' = 'WS_SEND_MESSAGE';
export const WS_CONNECTION_START_USERDATA: 'WS_CONNECTION_START_USERDATA' = 'WS_CONNECTION_START_USERDATA';

export const wsTypes = {
  start: WS_CONNECTION_START,
  sucess: WS_CONNECTION_SUCCESS,
  error: WS_CONNECTION_ERROR,
  closed: WS_CONNECTION_CLOSED,
  close: WS_CONNECTION_CLOSE,
  getMes: WS_GET_MESSAGE,
  getUsrOrd: WS_GET_USER_ORDERS,
  sendMes: WS_SEND_MESSAGE,
};