//список всех полученных ингредиентов
export const ALL_GET_INGREDIENTS_REQUEST = 'ALL_GET_INGREDIENTS_REQUEST';
export const ALL_GET_INGREDIENTS_SUCCESS = 'ALL_GET_INGREDIENTS_SUCCESS';
export const ALL_GET_INGREDIENTS_FAILURE = 'ALL_GET_INGREDIENTS_FAILURE';
//список всех ингредиентов в текущем конструкторе бургера
export const IN_CONSTRUCTOR_GET_INGREDIENTS = 'IN_CONSTRUCTOR_GET_INGREDIENTS';
export const IN_CONSTRUCTOR_GET_INGREDIENTS_SUCCESS = 'IN_CONSTRUCTOR_GET_INGREDIENTS_SUCCESS';
export const IN_CONSTRUCTOR_GET_INGREDIENTS_FAILURE = 'IN_CONSTRUCTOR_GET_INGREDIENTS_FAILURE';


export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
export const GET_CURRENT_INGREDIENT = 'GET_CURRENT_INGREDIENT';
