export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_INGREDIENTS_IN_CONSTRUCTOR = 'GET_INGREDIENTS_IN_CONSTRUCTOR';
export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
export const GET_CURRENT_INGREDIENT = 'GET_CURRENT_INGREDIENT';
